### ISSUE TITLE
Nets giftcards

### ISSUE THREAD

**Issue by royandre** [Nets-eCom/shopware6-easy-checkout#1]
It looks like this is for Nets Easy (not Nets Netaxept), and thus Nets Giftcards is not supported?

**Comment by Nets-LAKA-Mobile-SDK** [comment]
Hi @royandre  yes, this is correct, this plugin is for Nets Easy checkout which does not cover acceptance of Nets Giftcards as of now => https://developers.nets.eu/nets-easy/en-EU/docs/nets-easy-for-shopware/nets-easy-for-shopware-shopware-6/
