### ISSUE TITLE
Shopware 6.4.9.0 compatibility

### ISSUE THREAD

**Issue by edip123** [Nets-eCom/shopware6-easy-checkout#2]
When activating the plugin in Shopware 6.4.9.0 a fatal error is caused:
[2022-03-20T12:17:12.876628+00:00] php.CRITICAL: Fatal Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\OutOfMemoryError(code: 0): Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) at /www/htdocs/XXX/var/cache/prod_hf74a3c241ea607ac54deb4eeeeab949f/ContainerKiUcWQ0/Shopware_Production_KernelProdContainer.php:19958)"} []

**Comment by KNE-cc** [comment]
We got the same type of errors after updating to Shopware 6.4.9.0. This error occurs even if only this plugin is enabled and all others are disabled.

`[2022-03-31T15:43:11.557141+00:00] php.CRITICAL: Fatal Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\OutOfMemoryError(code: 0): Error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) at /var/www/shopware/var/cache/prod_h245f8c779e2aedc98bc8b941175f2ad5/ContainerVRax9PI/Shopware_Production_KernelProdContainer.php:18028)"} []`

**Comment by Nets-LAKA-Mobile-SDK** [comment]
Hi @edip123  and @KNE-cc,
Thank you for reporting this issue. Our team has acknowledged this issue and is looking into this. We will keep you posted upon progress.

**Comment by cybeerboy** [comment]
Any updates on this issue?

**Comment by KNE-cc** [comment]
The error also occur in Shopware Version 6.4.10.0 and 6.4.10.1 (today security hotfix)

**Comment by maunaw** [comment]
Hi @edip123, @KNE-cc , @cybeerboy 
We have released a new version with updates and fixes, request you to download it and let us know if any issues. The latest version 1.3.3 is compatible with 6.4.9.0 and also 6.4.10.1, Closing this issue as of now if there are any concerns, please reach out. Thank you.
