### ISSUE TITLE
Invalid header name with guzzlehttp/psr7 > 1.8.4

### ISSUE THREAD

**Issue by punknroll** [Nets-eCom/shopware6-easy-checkout#3]
With guzzlehttp/prs7 > 1.8.4 the header name is no longer valid, because it conains a ":":

https://github.com/Nets-eCom/shopware6-easy-checkout/blob/master/src/Service/Easy/Api/EasyApiService.php#L63

The check for a valid header is introduced in version 1.8.5:

https://github.com/guzzle/psr7/commit/902db15a551a4a415e732b622282e21ce1b508b4#diff-fb174524a7bba27ce140bc6ccd1c30811a6abeed9328e783b326189551ba7ed4R229

**Comment by maunaw** [comment]
Hi, Thank you for information, we have released a new version with few updates & fixes including this one.
