### ISSUE TITLE
Support headless

### ISSUE THREAD

**Issue by amin212121** [Nets-eCom/shopware6-easy-checkout#5]
Do you support headlles (pwa) SHopware?

**Comment by Nets-LAKA-Mobile-SDK** [comment]
Hi @amin212121 
This is not currently supported on Shopware. 
Unfortunately, we don't have it in short term roadmap but will look into it later in 2023.

**Comment by amin212121** [comment]
@Tim-Badin thx a lot. Looking forward 👍

**Comment by amin212121** [comment]
@Tim-Badin if you want you can close the issue but I recommend add label like roadmap but it's up to you
